services:
  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_URL: https://eb-tg.com
    volumes:
      - ./wordpress-files:/var/www/html  # Mount local wordpress-files directory
    depends_on:
      - db
    networks:
      - eb-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - db_data:/var/lib/mysql  # Mount MySQL data to keep the database persistent
      - ./backup.sql:/tmp/backup.sql  # Mount backup.sql to import the database
    networks:
      - eb-network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - wordpress
    networks:
        - eb-network


volumes:
  db_data:  # Declare volume for MySQL data

networks:
  eb-network:
    driver: bridge
